REGION_NAME = 'REGION_NAME'

DATA_S3_PATH = 'DATA_S3_PATH'

SAGEMAKER_S3_BUCKET = 'SAGEMAKER_S3_BUCKET'
INPUT_S3_PATH = 'sagemaker_input/input'
OUTPUT_S3_PATH = 'sagemaker_output/outputs'

MODEL_NAME = 'MODEL_NAME'
ENDPOINT_NAME = 'ENDPOINT_NAME'

SAGEMAKER_TRAINING_INSTANCE_TYPE = 'SAGEMAKER_TRAINING_INSTANCE_TYPE'
SAGEMAKER_HOSTING_INSTANCE_TYPE = 'SAGEMAKER_HOSTING_INSTANCE_TYPE'

SAGEMAKER_ROLE_ARN = 'SAGEMAKER_ROLE_ARN'